"""Cell 33 — inter-seat disagreement as a triage signal (observational).

Pre-registration: RUNBOOK_PAPER_HARDENING.md "CELL 33" (2026-08-09) and
"CELL 33 EXECUTION REGISTRATION" (2026-09-25). Population, instrument,
gate, estimators and decision rules are FROZEN there. No intervention:
every text judged here was generated by an earlier cell.

Stages (run in order; each is resumable, judgments are cached):
  build    zero model calls — freeze the population manifest
  gr       judge the G-R validation sample (both judges, both tasks),
           report the instrument gate and the attainability numbers
  judge    judge the remainder of the population, judge-major order
  measure  P33.1 / P33.2 under the frozen estimators

Run:  .venv/bin/python train/run_cell33_triage.py <stage>
"""
from __future__ import annotations

import glob
import hashlib
import json
import random
import re
import statistics
import sys
import time
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "gst" / "src"))

from examples.test_cases import get_case                  # noqa: E402
from train.run_cell25_moa import chat                     # noqa: E402

OUT = ROOT / "bench" / "analysis" / "cell33"
RUNS = ROOT / "bench" / "runs" / "imported"
MANIFEST = OUT / "manifest.json"
JUDGMENTS = OUT / "judgments.jsonl"
GR_REPORT = OUT / "gr_report.json"
MEASURE = OUT / "measured.json"

JUDGES = ("gpt-oss:20b", "qwen3-vl:30b-a3b-instruct")
WRITER_BACKEND = "ollama:gpt-oss:20b"
SEAT_TAGS = {
    "healthcare": "huggingface.co/mradermacher/Llama3-Med42-8B-GGUF:Q4_K_M",
    "legal": "huggingface.co/MaziyarPanahi/Saul-Instruct-v1-GGUF:Q4_K_M",
    "finance": "qwen-finance-r:coe",
}
SEAT_ORDER = ("healthcare", "legal", "finance")
PAIRS = (("healthcare", "legal"), ("healthcare", "finance"), ("legal", "finance"))
CASES = [f"case_{i}_" for i in range(1, 7)]
ARMS = {"arch-council", "c13-none", "c13-c1", "c13-c2", "c13-c3", "c13-c4",
        "c13-all", "c17-suppress", "c19-gated", "c20-decide", "c27-ledger",
        "c28-ledger-rep"}
SEAT_FLOOR = 200
FINAL_FLOOR = 500
GR_SEED = 33
GR_PER_CASE = 2
GR_MIN_ITEMS = 60
GR_BAR = 0.75
DRAWS = 5000
MAX_TOKENS = 4096

RUBRIC_SYSTEM = (
    "You are checking whether an ANSWER to a professional question addresses "
    "specific items. For each numbered item, reply on its own line with "
    "'N: YES' if the answer substantively does what the item describes, or "
    "'N: NO' if it does not. Judge only what is present in the answer. "
    "Output only these lines, one per item, nothing else.")

CONFLICT_SYSTEM = (
    "You are comparing specialist contributions written independently in "
    "response to the same question. Two contributions CONFLICT when one "
    "states a fact, figure, rule, timeline, or recommendation that the other "
    "contradicts or is incompatible with. Differences in emphasis, scope, "
    "level of detail, or topic are NOT conflicts. For each numbered pair, "
    "reply on its own line with 'N: YES' if the two contributions conflict "
    "on at least one substantive point, or 'N: NO' if they do not. Output "
    "only these lines, nothing else.")

_THINK = re.compile(r"<think>.*?</think>", re.DOTALL)
_LINE = re.compile(r"(\d+)\s*[:.)\-]\s*\**\s*(YES|NO)\b", re.IGNORECASE)


# ---------------------------------------------------------------- helpers
def tag_of(path: str) -> str:
    return Path(path).name.split("__")[-1].replace(".json", "")


def rubric_items(case_id: str) -> tuple[list[str], list[str]]:
    """(coverage items, red-flag items) — verbatim descriptions from the
    May 2026 case rubrics; must_have + should_have are coverage."""
    case = get_case(case_id)
    cov = [r.description for r in case.rubric
           if r.severity in ("must_have", "should_have")]
    red = [r.description for r in case.rubric
           if r.severity == "red_flag_if_present"]
    return cov, red


def parse_items(txt: str | None, n: int) -> list[str | None]:
    """Per-item 'YES'/'NO'/None. Duplicated item numbers with conflicting
    answers are None (quarantine), never defaulted (finding #2)."""
    out: list[str | None] = [None] * n
    if not txt:
        return out
    seen: dict[int, set[str]] = {}
    for m in _LINE.finditer(_THINK.sub("", txt)):
        i = int(m.group(1))
        if 1 <= i <= n:
            seen.setdefault(i, set()).add(m.group(2).upper())
    for i, vals in seen.items():
        if len(vals) == 1:
            out[i - 1] = next(iter(vals))
    return out


def load_cache() -> dict[tuple[str, str, str], dict]:
    cache = {}
    if JUDGMENTS.exists():
        for line in JUDGMENTS.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                cache[(r["judge"], r["run_id"], r["task"])] = r
    return cache


def append_cache(rec: dict) -> None:
    with JUDGMENTS.open("a") as fh:
        fh.write(json.dumps(rec) + "\n")


# ------------------------------------------------------------------ build
def stage_build() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for path in sorted(glob.glob(str(RUNS / "*.json"))):
        tag = tag_of(path)
        if tag not in ARMS:
            continue
        try:
            d = json.loads(Path(path).read_text())
        except Exception:                                  # noqa: BLE001
            continue
        if not any(d.get("case_id", "").startswith(c) for c in CASES):
            continue
        dl = d.get("deliberation") or {}
        if (dl.get("cabinet_backends") or {}).get("synthesis") != WRITER_BACKEND:
            continue
        seats = {}
        for t in dl.get("turns") or []:
            if isinstance(t, dict) and t.get("seat") in SEAT_TAGS \
                    and t.get("ollama_tag") == SEAT_TAGS[t["seat"]]:
                seats[t["seat"]] = t.get("output_text") or ""
        if set(seats) != set(SEAT_ORDER):
            continue
        if any(len(v) < SEAT_FLOOR for v in seats.values()):
            continue
        final = d.get("final_output") or ""
        if len(final) < FINAL_FLOOR:
            continue
        rows.append({"run_id": Path(path).name, "case": d["case_id"],
                     "arm": tag, "final_chars": len(final),
                     "seat_chars": {k: len(v) for k, v in seats.items()}})
    # G-R validation sample: seeded, GR_PER_CASE per case, stratified
    rng = random.Random(GR_SEED)
    by_case: dict[str, list[dict]] = {}
    for r in rows:
        by_case.setdefault(r["case"], []).append(r)
    gr_ids = set()
    for case in sorted(by_case):
        pool = sorted(by_case[case], key=lambda r: r["run_id"])
        gr_ids.update(r["run_id"] for r in rng.sample(pool, min(GR_PER_CASE, len(pool))))
    for r in rows:
        r["gr_sample"] = r["run_id"] in gr_ids
    items = {c: rubric_items(c) for c in sorted(by_case)}
    rubric_hash = hashlib.sha256(json.dumps(items, sort_keys=True).encode()).hexdigest()[:12]
    man = {"generated": time.strftime("%Y-%m-%d"), "n_runs": len(rows),
           "by_case": {c: len(v) for c, v in sorted(by_case.items())},
           "by_arm": {a: sum(1 for r in rows if r["arm"] == a) for a in sorted(ARMS)},
           "gr_sample_n": len(gr_ids),
           "gr_items": sum(len(items[r["case"]][0]) for r in rows if r["gr_sample"]),
           "rubric_hash": rubric_hash, "rubric": items, "runs": rows}
    MANIFEST.write_text(json.dumps(man, indent=1))
    print(f"population n={len(rows)}  cases={man['by_case']}")
    print(f"arms={man['by_arm']}")
    print(f"G-R sample: {len(gr_ids)} runs, {man['gr_items']} coverage items "
          f"(gate needs >= {GR_MIN_ITEMS})  rubric_hash={rubric_hash}")


# ------------------------------------------------------------------ judge
def load_run(run_id: str) -> tuple[str, dict[str, str], str]:
    d = json.loads((RUNS / run_id).read_text())
    q = get_case(d["case_id"]).prompt
    seats = {t["seat"]: t["output_text"] for t in d["deliberation"]["turns"]
             if isinstance(t, dict) and t.get("seat") in SEAT_TAGS}
    return q, seats, d["final_output"]


def judge_run(judge: str, run: dict, rubric: dict, cache: dict) -> None:
    q, seats, final = load_run(run["run_id"])
    cov, red = rubric[run["case"]]
    for task in ("rubric", "conflict"):
        key = (judge, run["run_id"], task)
        prev = cache.get(key)
        if prev and all(v is not None for v in prev["items"]):
            continue                                # complete; retry partials
        if task == "rubric":
            items = cov + red
            body = (f"QUESTION:\n{q}\n\nANSWER:\n{final}\n\nITEMS:\n" +
                    "\n".join(f"{i+1}. {it}" for i, it in enumerate(items)))
            raw = chat(judge, RUBRIC_SYSTEM, body, temperature=0.0,
                       max_tokens=MAX_TOKENS)
            parsed = parse_items(raw, len(items))
        else:
            body = (f"QUESTION:\n{q}\n\n" +
                    "\n\n".join(f"--- {s.upper()} CONTRIBUTION ---\n{seats[s]}"
                                for s in SEAT_ORDER) +
                    "\n\nPAIRS:\n" +
                    "\n".join(f"{i+1}. {a.upper()} vs {b.upper()}"
                              for i, (a, b) in enumerate(PAIRS)))
            raw = chat(judge, CONFLICT_SYSTEM, body, temperature=0.0,
                       max_tokens=MAX_TOKENS)
            parsed = parse_items(raw, len(PAIRS))
        rec = {"judge": judge, "run_id": run["run_id"], "task": task,
               "items": parsed, "raw": (raw or "")[-600:], "ts": time.time()}
        cache[key] = rec
        append_cache(rec)


def run_judging(subset: list[dict], label: str) -> None:
    man = json.loads(MANIFEST.read_text())
    rubric = {c: tuple(v) for c, v in man["rubric"].items()}
    cache = load_cache()
    t0 = time.time()
    for judge in JUDGES:                       # judge-major: one model resident
        done = 0
        for run in subset:
            judge_run(judge, run, rubric, cache)
            done += 1
            if done % 10 == 0:
                el = time.time() - t0
                print(f"  [{label}] {judge}: {done}/{len(subset)} runs, "
                      f"{el/60:.1f} min elapsed", flush=True)
    print(f"[{label}] judging complete in {(time.time()-t0)/60:.1f} min")


def stage_gr() -> None:
    man = json.loads(MANIFEST.read_text())
    sample = [r for r in man["runs"] if r["gr_sample"]]
    run_judging(sample, "G-R")
    report_gr(sample, man)


def stage_judge() -> None:
    if not GR_REPORT.exists() or not json.loads(GR_REPORT.read_text())["gate_pass"]:
        sys.exit("G-R gate not passed — Cell 33 is NOT RUNNABLE (reported as blocked)")
    man = json.loads(MANIFEST.read_text())
    rest = [r for r in man["runs"] if not r["gr_sample"]]
    run_judging(rest, "main")


# ---------------------------------------------------------------- measure
def per_run(run: dict, rubric: dict, cache: dict) -> dict | None:
    cov, red = rubric[run["case"]]
    ncov = len(cov)
    rj = [cache.get((j, run["run_id"], "rubric")) for j in JUDGES]
    cj = [cache.get((j, run["run_id"], "conflict")) for j in JUDGES]
    if any(x is None for x in rj + cj):
        return None
    a, b = rj[0]["items"], rj[1]["items"]
    both = [(a[i], b[i]) for i in range(ncov) if a[i] is not None and b[i] is not None]
    if len(both) < max(1, ncov - 2):          # >2 unparsed coverage items: drop
        return None
    coverage = sum(1 for x, y in both if x == "YES" and y == "YES") / len(both)
    cov_a = sum(1 for x, _ in both if x == "YES") / len(both)
    cov_b = sum(1 for _, y in both if y == "YES") / len(both)
    agree_items = [(x == y) for x, y in both]
    reds = [(a[ncov + i], b[ncov + i]) for i in range(len(red))]
    red_both = sum(1 for x, y in reds if x == "YES" and y == "YES")
    ca, cb = cj[0]["items"], cj[1]["items"]
    pairs = [(ca[i], cb[i]) for i in range(len(PAIRS))]
    if any(x is None or y is None for x, y in pairs):
        return None
    conflict_both = sum(1 for x, y in pairs if x == "YES" and y == "YES")
    conflict_either = sum(1 for x, y in pairs if x == "YES" or y == "YES")
    conflict_agree = [(x == y) for x, y in pairs]
    return {"run_id": run["run_id"], "case": run["case"], "arm": run["arm"],
            "coverage": coverage, "cov_a": cov_a, "cov_b": cov_b,
            "n_items": len(both), "agree_items": agree_items,
            "red_both": red_both, "n_red": len(red),
            "conflict": conflict_both, "conflict_either": conflict_either,
            "conflict_agree": conflict_agree}


def report_gr(sample: list[dict], man: dict) -> None:
    rubric = {c: tuple(v) for c, v in man["rubric"].items()}
    cache = load_cache()
    rows = [x for x in (per_run(r, rubric, cache) for r in sample) if x]
    agree = [v for r in rows for v in r["agree_items"]]
    cagree = [v for r in rows for v in r["conflict_agree"]]
    n_items = len(agree)
    rate = sum(agree) / n_items if n_items else 0.0
    gate = n_items >= GR_MIN_ITEMS and rate >= GR_BAR
    conf = [r["conflict"] for r in rows]
    cov = [r["coverage"] for r in rows]
    dist = {k: conf.count(k) for k in range(4)}
    modal_share = max(dist.values()) / len(conf) if conf else 1.0
    rep = {"n_runs": len(rows), "n_rubric_items": n_items,
           "rubric_agreement": round(rate, 3), "gate_bar": GR_BAR,
           "gate_min_items": GR_MIN_ITEMS, "gate_pass": bool(gate),
           "conflict_item_agreement": round(sum(cagree) / len(cagree), 3) if cagree else None,
           "conflict_score_dist": dist, "conflict_modal_share": round(modal_share, 3),
           "conflict_degenerate": modal_share >= 0.90,
           "coverage_mean": round(statistics.mean(cov), 3) if cov else None,
           "coverage_sd": round(statistics.pstdev(cov), 3) if len(cov) > 1 else None}
    GR_REPORT.write_text(json.dumps(rep, indent=1))
    print(json.dumps(rep, indent=1))
    print("G-R GATE:", "PASS — Cell 33 runnable" if gate else
          "FAIL — Cell 33 NOT RUNNABLE, reported as blocked")
    if rep["conflict_degenerate"]:
        print("ATTAINABILITY WARNING: conflict score is near-degenerate in the "
              "sample (>=90% one value); if this holds in the population "
              "P33.1/P33.2 are NOT EVALUABLE by construction (registered rule).")


def demean(rows: list[dict], key: str) -> list[float]:
    """Within case x arm centering (the registered fixed effects)."""
    groups: dict[tuple, list[float]] = {}
    for r in rows:
        groups.setdefault((r["case"], r["arm"]), []).append(r[key])
    means = {g: sum(v) / len(v) for g, v in groups.items()}
    return [r[key] - means[(r["case"], r["arm"])] for r in rows]


def slope(xs: list[float], ys: list[float]) -> float | None:
    n = len(xs)
    if n < 3:
        return None
    mx, my = sum(xs) / n, sum(ys) / n
    sxx = sum((x - mx) ** 2 for x in xs)
    if sxx == 0:
        return None
    return sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sxx


def cluster_boot(rows: list[dict], stat, draws: int = DRAWS, seed: int = 0):
    rng = random.Random(seed)
    cases = sorted({r["case"] for r in rows})
    by = {c: [r for r in rows if r["case"] == c] for c in cases}
    vals = []
    for _ in range(draws):
        pick = [rng.choice(cases) for _ in cases]
        boot = [r for c in pick for r in by[c]]
        v = stat(boot)
        if v is not None:
            vals.append(v)
    vals.sort()
    if not vals:
        return None, None
    return vals[int(0.025 * len(vals))], vals[int(0.975 * len(vals))]


def stage_measure() -> None:
    man = json.loads(MANIFEST.read_text())
    rubric = {c: tuple(v) for c, v in man["rubric"].items()}
    cache = load_cache()
    rows = [x for x in (per_run(r, rubric, cache) for r in man["runs"]) if x]
    n = len(rows)
    print(f"analysable runs: {n} / {man['n_runs']}")
    agree = [v for r in rows for v in r["agree_items"]]
    cagree = [v for r in rows for v in r["conflict_agree"]]
    out: dict = {"n_runs": n, "n_population": man["n_runs"],
                 "rubric_item_agreement": round(sum(agree) / len(agree), 3),
                 "conflict_item_agreement": round(sum(cagree) / len(cagree), 3),
                 "coverage_mean": round(statistics.mean(r["coverage"] for r in rows), 3),
                 "conflict_dist": {k: sum(1 for r in rows if r["conflict"] == k) for k in range(4)},
                 "red_flag_rate": round(sum(r["red_both"] for r in rows) /
                                        max(1, sum(r["n_red"] for r in rows)), 3)}
    modal = max(out["conflict_dist"].values()) / n
    out["conflict_modal_share"] = round(modal, 3)
    if modal >= 0.90:
        out["verdict"] = {"P33.1": "NOT EVALUABLE (degenerate predictor)",
                          "P33.2": "NOT EVALUABLE (degenerate predictor)"}
        MEASURE.write_text(json.dumps(out, indent=1))
        print(json.dumps(out, indent=1))
        return

    # P33.1 — within case x arm slope of coverage on conflict score
    def fe_slope(rs):
        return slope(demean(rs, "conflict"), demean(rs, "coverage"))
    s = fe_slope(rows)
    lo, hi = cluster_boot(rows, fe_slope)
    raw_s = slope([r["conflict"] for r in rows], [r["coverage"] for r in rows])
    out["P33.1"] = {"slope_fe": round(s, 4), "ci": [round(lo, 4), round(hi, 4)],
                    "slope_raw": round(raw_s, 4),
                    "verdict": ("SUPPORTED" if hi < 0 else
                                "FALSIFIED (CI includes 0 or positive)")}
    # sensitivity: either-judge conflict
    def fe_slope_e(rs):
        return slope(demean(rs, "conflict_either"), demean(rs, "coverage"))
    s2 = fe_slope_e(rows)
    lo2, hi2 = cluster_boot(rows, fe_slope_e, seed=1)
    out["P33.1_sensitivity_either"] = {"slope_fe": round(s2, 4),
                                       "ci": [round(lo2, 4), round(hi2, 4)]}

    # P33.2 — abstain on the top quartile of conflict; retention reported
    scores = sorted(r["conflict"] for r in rows)
    q75 = scores[int(0.75 * (n - 1))]
    rule = None
    for thr, cmp in ((q75, "gt"), (q75, "ge")):
        keep = [r for r in rows if (r["conflict"] <= thr if cmp == "gt"
                                    else r["conflict"] < thr)]
        ret = len(keep) / n
        if 0.50 <= ret <= 0.95:
            rule = (thr, cmp, ret)
            break
    if rule is None:
        out["P33.2"] = {"verdict": "NOT EVALUABLE (no threshold retains 50-95%)",
                        "q75": q75}
    else:
        thr, cmp, ret = rule

        def gain(rs):
            keep = [r for r in rs if (r["conflict"] <= thr if cmp == "gt"
                                      else r["conflict"] < thr)]
            if not keep or len(keep) == len(rs):
                return None
            return (sum(r["coverage"] for r in keep) / len(keep) -
                    sum(r["coverage"] for r in rs) / len(rs))
        g = gain(rows)
        glo, ghi = cluster_boot(rows, gain, seed=2)
        out["P33.2"] = {"abstain_rule": f"conflict {'>' if cmp == 'gt' else '>='} {thr}",
                        "retention": round(ret, 3), "gain": round(g, 4),
                        "ci": [round(glo, 4), round(ghi, 4)],
                        "verdict": ("SUPPORTED" if glo > 0 else
                                    "FALSIFIED (CI includes 0 or negative)")}
    # descriptive per-arm means
    out["per_arm"] = {a: {"n": sum(1 for r in rows if r["arm"] == a),
                          "coverage": round(statistics.mean(r["coverage"] for r in rows if r["arm"] == a), 3),
                          "conflict": round(statistics.mean(r["conflict"] for r in rows if r["arm"] == a), 3)}
                      for a in sorted({r["arm"] for r in rows})}
    MEASURE.write_text(json.dumps(out, indent=1))
    print(json.dumps(out, indent=1))


if __name__ == "__main__":
    stage = sys.argv[1] if len(sys.argv) > 1 else ""
    {"build": stage_build, "gr": stage_gr, "judge": stage_judge,
     "measure": stage_measure}.get(stage, lambda: sys.exit(__doc__))()
